### ISSUE TITLE
WITH_OPENCL_SUPPORT in Packet_pipeline.cpp? OpenCL not work on Windows

### ISSUE THREAD

**Issue by Edwinzero** [OpenKinect/libfreenect2#110]
My libfreenect2 with huge latency which I think it is not using OpenCL, after I check packet_pipeline.cpp, I found WITH_OPENCL_SUPPORT is not using... 
![image](https://cloud.githubusercontent.com/assets/5100412/5306375/e747a5b6-7bd1-11e4-8d74-f23c4c406741.png)
How to configure that implement with OpenCL?
I did this based on @larshg 's solution in opencl_depth_packet_processor.cpp
![image](https://cloud.githubusercontent.com/assets/5100412/5306418/43d2f5e2-7bd2-11e4-97fb-e9fa591e62c2.png)

**Comment by christiankerl** [comment]
solved with recent changes?

**Comment by Edwinzero** [comment]
It solved~ code can be executed now~
I changed this part and it seems work now, thank you a lot. But I don't know the reason why the fps still can't reach the real time. And I am using the OpenCL from CUDA whose header file is slight different with khronos' one. I found the Cmake file for openCL is for general but this file is not working with the  CUDA version on my computer. So if you could have time to briefly explain this part for me I will be so appreciated. @christiankerl

**Comment by larshg** [comment]
Hey @Edwinzero
 
I don't think Nvidia is supporting opencl 1.2 (i don't know if this is actually used, mayby @wiedemeyer know this? - see discussion in this thread:

https://devtalk.nvidia.com/default/topic/540773/announcements/opencl-1-2-support-in-nvidia-drivers/

So you properly won't able to get the opencl working on a Nvidia GPU (atleast I had problems too). I guess if you have a CPU with integrated GPU, you could try out Intels implementation of OpenCL.

Else you would have to use OpenGL which should be possible or contribute with a CUDA implementation :)

Regards, Lars

**Comment by wiedemeyer** [comment]
The OpenCL implementation does not use anything that is OpenCL 1.2 specific. It also works with OpenCL 1.1 and should (but never tested) work with OpenCL 1.0.
I am using the OpenCL implementation on different systems. It works on nvidia (I tested it on 640, 670, 770, 970), AMD and Intel.
I think there is no need for a CUDA implementation, because OpenCL works on platforms from all vendors, while CUDA is proprietary and nvidia only.

**Comment by larshg** [comment]
Ahh great :) - Have you compiled on each test machine, or just transferred a compiled version? I think there might be some difference in the available includes from nvidia (toolkit) - compared to ATI/intel/Khronos? I can't confirm it right now, as I'm not home at my pc with nvidia gpu - but I'll try look at it when I get the time.

Then its probably not necessary with a CUDA implementation :)

**Comment by wiedemeyer** [comment]
Yes I compiled it an all. But I am working on Ubuntu.
You could hard code which OpenCL version you want to use, that might solve it:
```
#define CL_USE_DEPRECATED_OPENCL_1_1_APIS
#define __CL_ENABLE_EXCEPTIONS
#ifdef __APPLE__
  #include <OpenCL/cl.hpp>
#else
  #include <CL/cl.h>
  #undef CL_VERSION_1_2
  #include <CL/cl.hpp>
#endif
```

**Comment by Edwinzero** [comment]
Hey guys, here is the file organization which locates the CL in the CUDA include folder...
![image](https://cloud.githubusercontent.com/assets/5100412/5839174/76ed512c-a15a-11e4-9ee7-1ddf43c768dc.png)
And I am wondering if you could tell me whether these header files are same with the Khronos one? Because I can't find the website for downloading Khronos version for intel CPU... If you could give me an address I will be appreciated. 
Thank you guys!

**Comment by floe** [comment]
Still an issue? Otherwise, please close.
